"""Synchronize language sources and generate Minecraft language storage.

The Chinese language file is the source of truth for both keys and key order.
Other language files are completed from that source without losing existing
translations.

scripts/todo_translate.yml is a small YAML translation workbench. Each pending entry
stores the source value and an editable translation field:

    languages:
      en_us:
        some_key:
          source: "Chinese text"
          translation: null

When ``translation`` is filled in, the next run writes it to the language file
and removes the completed entry from the workbench.
"""

from __future__ import annotations

import argparse
import itertools
import re
from collections import OrderedDict
from dataclasses import dataclass
from functools import lru_cache
from pathlib import Path
from typing import Any

import yaml


PARAMETER_RE = re.compile(r"%(?:(\d+)\$)?s")
TODO_HEADER = (
    "# Translation workbench generated by scripts/lang/sync_lang.py\n"
    "# Fill a translation value and run the script to apply it.\n"
    "# Keep translation as null when the entry is not translated yet.\n"
)

LanguageData = OrderedDict[str, Any]
WorkbenchEntry = dict[str, Any]
Workbench = OrderedDict[str, OrderedDict[str, WorkbenchEntry]]

BASE_LANG_FILE = "zh_cn.yml"
CORE_LANGUAGES = {"zh_cn", "en_us", "zh_tw", "ja_jp"}

ROOT = Path(__file__).resolve().parents[2]
LANG_DIR = ROOT / "scripts" / "lang"
TODO_PATH = ROOT / "scripts" / "todo_translate.yml"


@dataclass(frozen=True)
class GeneratedTarget:
    path: Path
    pretty: bool


CORE_TARGETS = (
    GeneratedTarget(
        ROOT / "src/+mc1.15/data/tpa/functions/init_storage_lang.mcfunction",
        pretty=False,
    ),
    GeneratedTarget(
        ROOT
        / "src/+mc1.20.2/format_1_20_5/data/tpa/functions/init_storage_lang.mcfunction",
        pretty=True,
    ),
    GeneratedTarget(
        ROOT / "src/+mc1.20.2/data/tpa/function/init_storage_lang.mcfunction",
        pretty=True,
    ),
)

EXTRA_TARGETS = (
    GeneratedTarget(
        ROOT / "src/lang_extra/data/tpa_extra/functions/init_storage_lang.mcfunction",
        pretty=False,
    ),
    GeneratedTarget(
        ROOT / "src/lang_extra/data/tpa_extra/function/init_storage_lang.mcfunction",
        pretty=True,
    ),
)


def load_yaml(path: Path, default: Any) -> Any:
    """Load one YAML file, returning ``default`` when it is absent or empty."""

    if not path.exists():
        return default

    with path.open("r", encoding="utf-8") as stream:
        return yaml.safe_load(stream) or default


def normalize_language_data(data: Any) -> OrderedDict[str, Any]:
    """Normalize supported language-file shapes into an ordered mapping."""

    if isinstance(data, list):
        if not data or not isinstance(data[0], dict):
            return OrderedDict()
        data = data[0]

    if not isinstance(data, dict):
        return OrderedDict()

    return OrderedDict(data.items())


def language_code(path: Path, data: LanguageData) -> str:
    """Return the language identifier used by the generated storage."""

    name = data.get("name")
    return name if isinstance(name, str) and name else path.stem


def plain_data(value: Any) -> Any:
    """Convert ordered mappings into regular mappings accepted by PyYAML."""

    if isinstance(value, dict):
        return {key: plain_data(item) for key, item in value.items()}
    if isinstance(value, list):
        return [plain_data(item) for item in value]
    return value


def save_yaml(
    path: Path,
    data: LanguageData,
    previous_data: LanguageData,
) -> bool:
    """Write a language file only when its ordered data actually changed."""

    if list(previous_data.items()) == list(data.items()):
        return False

    return write_text_if_changed(path, dump_yaml(data))


def dump_yaml(data: Any) -> str:
    """Serialize YAML with stable ordering and readable Unicode text."""

    return yaml.safe_dump(
        plain_data(data),
        allow_unicode=True,
        default_flow_style=False,
        sort_keys=False,
        width=120,
    )


def write_text_if_changed(path: Path, content: str) -> bool:
    """Write a generated file only when its exact content has changed."""

    if path.exists() and path.read_text(encoding="utf-8") == content:
        return False

    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")
    return True


def load_workbench() -> Workbench:
    """Read the editable translation workbench.

    The old generated format contained only ``[language]`` sections followed
    by key names. It is migrated in memory and written in the new YAML format
    on the next normal run.
    """

    if not TODO_PATH.exists():
        return OrderedDict()

    try:
        raw = load_yaml(TODO_PATH, {})
    except yaml.YAMLError:
        # The old section-based file is not valid YAML. It is still supported
        # so the first run can migrate it instead of losing its pending keys.
        return load_legacy_workbench()
    if isinstance(raw, dict) and isinstance(raw.get("languages"), dict):
        result: Workbench = OrderedDict()
        for language, entries in raw["languages"].items():
            if not isinstance(entries, dict):
                continue
            result[language] = OrderedDict()
            for key, entry in entries.items():
                if not isinstance(entry, dict):
                    continue

                # ``value`` was used by an earlier workbench draft. Accept it
                # so an unfinished workbench can be upgraded without loss.
                if "translation" in entry:
                    translation = entry.get("translation")
                else:
                    translation = entry.get("value")
                    if translation == entry.get("source"):
                        # The earlier draft used the source text as its
                        # pending placeholder. In the new format null means
                        # pending, so do not complete it during migration.
                        translation = None

                result[language][key] = {
                    "source": entry.get("source"),
                    "translation": translation,
                }
        return result

    return load_legacy_workbench()


def load_legacy_workbench() -> Workbench:
    """Parse the previous section-based workbench format."""

    result: Workbench = OrderedDict()
    language = None

    for line in TODO_PATH.read_text(encoding="utf-8").splitlines():
        line = line.strip()
        if not line or line.startswith("#"):
            continue
        if line.startswith("[") and line.endswith("]"):
            language = line[1:-1].strip()
            result.setdefault(language, OrderedDict())
            continue
        if language is not None:
            result[language][line] = {"source": None, "translation": None}

    return result


def save_workbench(
    workbench: Workbench,
) -> bool:
    """Persist the workbench without rewriting it when nothing changed."""

    document: OrderedDict[str, Any] = OrderedDict()
    document["languages"] = workbench
    return write_text_if_changed(TODO_PATH, TODO_HEADER + dump_yaml(document))


def ordered_language_data(
    base_data: LanguageData,
    language_data: LanguageData,
) -> LanguageData:
    """Return only base-language keys, in the base-language order.

    The base language defines both the supported key set and its order.
    Target-only keys are stale by definition and must not be appended back to
    the synchronized language file.
    """

    return OrderedDict(
        (key, language_data[key])
        for key in base_data
        if key in language_data
    )


def ordered_workbench(
    workbench: Workbench,
    base_data: LanguageData,
) -> Workbench:
    """Keep pending entries only for keys that still exist in the base language."""

    ordered: Workbench = OrderedDict()
    for language, entries in workbench.items():
        ordered_entries = OrderedDict(
            (key, entries[key]) for key in base_data if key in entries
        )
        if ordered_entries:
            ordered[language] = ordered_entries
    return ordered


def apply_workbench_translation(
    entries: OrderedDict[str, WorkbenchEntry],
    key: str,
    source: Any,
    current_value: Any,
) -> tuple[bool, Any]:
    """Resolve one existing workbench entry.

    Return ``(completed, value)``. A completed entry is removed by the caller;
    ``value`` is either the workbench translation or the current language-file
    value when an old key-only entry was completed directly in that file.
    """

    entry = entries.get(key)
    if entry is None:
        return False, None

    old_source = entry.get("source")
    translation = entry.get("translation")

    # Legacy entries did not store their source/translation. The old target
    # value is the safest migration value, while the base value becomes the
    # source.
    if old_source is None and translation is None:
        entry["source"] = source
        if current_value is not None and current_value != source:
            return True, current_value
        return False, None

    # A pending fallback follows changes in the base language automatically.
    if translation is None:
        entry["source"] = source
        return False, None

    # A non-null translation means the user completed this entry in the
    # workbench. Apply it to the language file and remove the entry.
    if current_value in (None, old_source, source, translation):
        return True, translation

    print(
        f"  ! conflict: {key} already differs in the language file; "
        "kept the workbench entry"
    )
    return False, None


def synchronize_language(
    language: str,
    base_data: LanguageData,
    language_data: LanguageData,
    workbench: Workbench,
) -> tuple[LanguageData, int, int]:
    """Merge one language file and return data plus added/completed counts."""

    entries = workbench.setdefault(language, OrderedDict())
    added = 0
    completed = 0

    for key, source in base_data.items():
        if key not in language_data:
            language_data[key] = source
            if key not in entries:
                entries[key] = {"source": source, "translation": None}
                added += 1

        completed_entry, translated_value = apply_workbench_translation(
            entries,
            key,
            source,
            language_data[key],
        )
        if completed_entry:
            language_data[key] = translated_value
            del entries[key]
            completed += 1

    return ordered_language_data(base_data, language_data), added, completed


@lru_cache(maxsize=None)
def permutation_index(order: tuple[int, ...]) -> int | None:
    """Return the legacy format index for a placeholder order."""

    if len(order) <= 1:
        return None

    for index, permutation in enumerate(itertools.permutations(range(1, len(order) + 1))):
        if permutation == order:
            return index
    return None


def convert_language_value(value: str) -> tuple[str | list[str], int | None]:
    """Split %s/%n$s placeholders for generated Minecraft storage."""

    matches = list(PARAMETER_RE.finditer(value))
    if not matches:
        return value, None

    parts: list[str] = []
    order: list[int] = []
    last_end = 0

    for index, match in enumerate(matches, start=1):
        parts.append(value[last_end : match.start()])
        order.append(int(match.group(1)) if match.group(1) else index)
        last_end = match.end()

    parts.append(value[last_end:])
    return parts, permutation_index(tuple(order))


def escape_snbt_string(value: str) -> str:
    return value.replace("\\", "\\\\").replace('"', '\\"')


def snbt_compound(data: dict[str, Any], pretty: bool) -> str:
    parts = []
    for key, value in data.items():
        if isinstance(value, str):
            converted, format_index = convert_language_value(value)
            if isinstance(converted, str):
                parts.append(f'{key}: "{escape_snbt_string(converted)}"')
            else:
                values = ", ".join(
                    f'"{escape_snbt_string(part)}"' for part in converted
                )
                parts.append(f"{key}: [{values}]")
                if format_index is not None:
                    parts.append(f"{key}_format: {format_index}")
        else:
            parts.append(f"{key}: {value}")

    if pretty:
        return "{\\\n    " + ", \\\n    ".join(parts) + " \\\n}"
    return "{" + ", ".join(parts) + "}"


def snbt_list(items: list[str], pretty: bool) -> str:
    if pretty:
        return "[ \\\n  " + ", \\\n  ".join(items) + " \\\n]"
    return "[" + ", ".join(items) + "]"


def generate_mcfunction(
    language_data: OrderedDict[str, LanguageData],
    pretty: bool,
    extra: bool,
) -> str:
    compounds = [] if extra else ["{id: 0}"]
    for language, data in language_data.items():
        compounds.append(snbt_compound({"lang": language, **data}, pretty))

    prefix = "data modify storage tpa:tpa temp.lang set value "
    if pretty:
        prefix += "\\\n"

    return (
        f"{prefix}{snbt_list(compounds, pretty)}\n"
        "data modify storage tpa:tpa lang append from storage tpa:tpa temp.lang[]\n"
    )


def write_generated_targets(
    all_languages: OrderedDict[str, LanguageData],
) -> None:
    core = OrderedDict(
        (language, data)
        for language, data in all_languages.items()
        if language in CORE_LANGUAGES
    )
    extra = OrderedDict(
        (language, data)
        for language, data in all_languages.items()
        if language not in CORE_LANGUAGES
    )

    for target in CORE_TARGETS:
        changed = write_text_if_changed(
            target.path,
            generate_mcfunction(core, target.pretty, extra=False),
        )
        marker = "updated" if changed else "unchanged"
        print(f"[CORE] {target.path} <- {', '.join(core)} ({marker})")

    for target in EXTRA_TARGETS:
        changed = write_text_if_changed(
            target.path,
            generate_mcfunction(extra, target.pretty, extra=True),
        )
        marker = "updated" if changed else "unchanged"
        print(
            f"[EXTRA] {target.path} <- "
            f"{', '.join(extra) or '(none)'} ({marker})"
        )


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="validate and report changes without writing language or workbench files",
    )
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    base_data = normalize_language_data(load_yaml(LANG_DIR / BASE_LANG_FILE, {}))
    if not base_data:
        raise SystemExit(
            f"Base language is empty or missing: {LANG_DIR / BASE_LANG_FILE}"
        )

    workbench = load_workbench()
    all_languages: OrderedDict[str, LanguageData] = OrderedDict()
    all_languages["zh_cn"] = base_data

    print("== Synchronizing language files ==")
    for language_path in sorted(LANG_DIR.glob("*.yml")):
        if language_path.name == BASE_LANG_FILE:
            continue

        language_data = normalize_language_data(load_yaml(language_path, {}))
        previous_data = OrderedDict(language_data)
        language_name = language_code(language_path, language_data)
        language_data, added, completed = synchronize_language(
            language_name,
            base_data,
            language_data,
            workbench,
        )
        all_languages[language_name] = language_data

        if args.check:
            print(f"[CHECK] {language_path.name}: +{added}, completed {completed}")
        else:
            changed = save_yaml(language_path, language_data, previous_data)
            marker = "updated" if changed else "unchanged"
            print(
                f"[{language_path.name}] +{added}, completed {completed}, {marker}"
            )

    # Keep pending entries in base-language order and remove entries whose keys
    # were deleted from the base language.
    workbench = ordered_workbench(workbench, base_data)

    if args.check:
        pending = sum(len(entries) for entries in workbench.values())
        print(f"[CHECK] pending translation entries: {pending}")
        return

    print(
        f"[{TODO_PATH.relative_to(ROOT)}] "
        + ("updated" if save_workbench(workbench) else "unchanged")
    )
    print("\n== Generating mcfunction files ==")
    write_generated_targets(all_languages)
    print("\nsync_lang.py completed")


if __name__ == "__main__":
    main()
